server:
  port: 8080
mybatis-plus:
  type-aliases-package: cn.hwz.learn.sharingjdbc.mybatis.domain
  mapper-locations: classpath:mappers/*xml

spring:
  application:
    name: SharingjdbcLearn
  shardingsphere:
    mode:
      type: Memory
    datasource:
      name: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://192.168.244.129:3306/learn_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useCursorFetch=true&autoReconnect=true&useLocalSessionState=true
        username: root
        password: root
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://192.168.244.130:3306/learn_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useCursorFetch=true&autoReconnect=true&useLocalSessionState=true
        username: root
        password: root

    rules:
      tables:
        sharingjdbc:
          actualDataNodes: ds$->{0..1}.sharingjdbc_$->{0..1}
          tableStrategy:
            standard:
              shardingColumn: id
              shardingAlgorithmName: id-inline
          keyGenerateStrategy:
            column: id
            keyGeneratorName: snowflake
      defaultShardingColumn: id
      defaultDatabaseStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: database-inline
      defaultTablesStrategy:
        none:

      keyGenerators:
        snowflake:
          type: SNOWFLAKE

      shardingAlgorithms:
        database-inline:
          type: INLINE
          props:
            algorithm-expression: ds$->{id % 2}
        id-inline:
          type: INLINE
          props:
            algorithm-expression: sharingjdbc_$->{id % 2}
        item-inline:
          type: INLINE
          props:
            algorithm-expression: ds$->{sharing_id % 2}
    props:
      sql-show: true

logging:
  level:
    org.apache.shardingsphere: DEBUG  # 显示分片路由过程
    org.mybatis: TRACE